export const FETCH_PROFILE_SET = 'FETCH_PROFILE_SET';
export const FETCH_PROFILE_SET_LOADING = 'FETCH_PROFILE_SET_LOADING';
export const FETCH_PROFILE_REMOVE_LOADING = 'FETCH_PROFILE_REMOVE_LOADING';

export const FETCH_USERS_ADD = 'FETCH_USERS_ADD';
export const FETCH_USERS_DELETE = 'FETCH_USERS_DELETE';
export const FETCH_USERS_GET = 'FETCH_USERS_GET';
export const FETCH_USERS_OFF = 'FETCH_USERS_OFF';

export const FETCH_MESSAGES_ADD = 'FETCH_MESSAGES_ADD';
export const FETCH_MESSAGES_SET = 'FETCH_MESSAGES_SET';
export const FETCH_MESSAGES_DEL = 'FETCH_MESSAGES_DEL';